// Code generated by tools/invariant-gen (TriggerA:BlindSpot); review before merging on an invariant/* branch.
package invariants

import (
	"fmt"
	"strings"
	"time"

	corev1 "k8s.io/api/core/v1"

	pmv1alpha1 "github.com/gke-labs/pod-migration/controller/api/v1alpha1"
)

// RuleI10 returns the stateless Rule for I10 (RestoringReplacementLiveness).
//
// Trigger: TriggerA:BlindSpot
// Summary: PMJ "pmj-wedge-0" remained in PhaseRestoring >=30s after bound replacement pod "t3-counter-0-dst" was deleted or missing from NamespacePods
func RuleI10() Rule {
	return funcRule{
		id:   "I10",
		name: "RestoringReplacementLiveness",
		fn:   EvaluateI10_RestoringReplacementLiveness,
	}
}

// EvaluateI10_RestoringReplacementLiveness evaluates I10 (RestoringReplacementLiveness) over a point-in-time ReconcileSnapshot.
func EvaluateI10_RestoringReplacementLiveness(s *ReconcileSnapshot) []Violation {
	if s == nil || s.PrimaryPMJ == nil {
		return nil
	}
	pmj := s.PrimaryPMJ
	_ = fmt.Sprintf
	_ = strings.TrimSpace
	_ = time.Second
	_ = corev1.ConditionTrue
	_ = pmv1alpha1.PodMigrationJobPhaseRestoring
	// RestoringReplacementLiveness: when a PMJ has remained in PhaseRestoring
	// for >=30s with a bound RestoredPodName, that replacement pod must still
	// exist and be non-deleting in the namespace (including single-pod namespaces
	// where NamespacePods is empty after source eviction; see Issue #88 / PR #90
	// for PodListFailed). Because point-in-time absence evaluation is single-sample,
	// I10 is intended for --invariant-mode=observe until multi-reconcile debounce
	// persistence is added to Engine for absence-style rules (Issue #99).
	if (s.Reconciler == "" || s.Reconciler == "PodMigrationJobReconciler") &&
		pmj.Status.Phase == pmv1alpha1.PodMigrationJobPhaseRestoring &&
		pmj.Status.RestoredPodName != "" &&
		pmj.Status.RestoringStartTime != nil &&
		!s.Now.IsZero() &&
		s.Now.Sub(pmj.Status.RestoringStartTime.Time) >= 30*time.Second {
		found := false
		for i := range s.NamespacePods {
			pod := &s.NamespacePods[i]
			if (pod.Namespace == "" || pmj.Namespace == "" || pod.Namespace == pmj.Namespace) &&
				pod.Name == pmj.Status.RestoredPodName && pod.DeletionTimestamp == nil {
				found = true
				break
			}
		}
		if !found && s.PrimaryPod != nil &&
			(s.PrimaryPod.Namespace == "" || pmj.Namespace == "" || s.PrimaryPod.Namespace == pmj.Namespace) &&
			s.PrimaryPod.Name == pmj.Status.RestoredPodName && s.PrimaryPod.DeletionTimestamp == nil {
			found = true
		}
		if !found {
			return []Violation{{
				InvariantID:   "I10",
				InvariantName: "RestoringReplacementLiveness",
				Reason:        "RestoringReplacementPodMissing",
				Message:       fmt.Sprintf("PMJ %s/%s remained in PhaseRestoring >=30s while replacement pod %q is missing or deleting", pmj.Namespace, pmj.Name, pmj.Status.RestoredPodName),
				Namespace:     pmj.Namespace,
				PMJName:       pmj.Name,
				PodName:       pmj.Status.RestoredPodName,
			}}
		}
	}
	return nil
}
