// Code generated by tools/invariant-gen (TriggerA:BlindSpot); review before merging on an invariant/* branch.
package invariants

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

func TestI10_RestoringReplacementLiveness_RedProof(t *testing.T) {
	fixturePath := filepath.Join("testdata", "i10_wedged_restoring_orphan_snapshot.json")
	raw, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("read RED snapshot fixture %s: %v", fixturePath, err)
	}
	var snap ReconcileSnapshot
	if err := json.Unmarshal(raw, &snap); err != nil {
		t.Fatalf("unmarshal RED snapshot fixture %s into ReconcileSnapshot: %v", fixturePath, err)
	}
	rule := RuleI10()
	vs := rule.Evaluate(&snap)
	if len(vs) == 0 {
		t.Fatalf("RED proof failed: expected >= 1 violation from %s (%s) on offending fixture %s, got 0", rule.ID(), rule.Name(), fixturePath)
	}
	if vs[0].InvariantID != "I10" {
		t.Fatalf("expected violation InvariantID=I10, got %q", vs[0].InvariantID)
	}

	// RED coverage for PrimaryPod fallback when NamespacePods is empty and PrimaryPod is nil
	emptyPodsSnap := snap
	emptyPodsSnap.NamespacePods = nil
	emptyPodsSnap.PrimaryPod = nil
	vsEmpty := rule.Evaluate(&emptyPodsSnap)
	if len(vsEmpty) == 0 {
		t.Fatalf("RED proof failed on empty NamespacePods + nil PrimaryPod fallback path: expected >= 1 violation, got 0")
	}
	if vsEmpty[0].InvariantID != "I10" {
		t.Fatalf("expected violation InvariantID=I10 on empty NamespacePods fallback path, got %q", vsEmpty[0].InvariantID)
	}

	// Verify !s.PodListFailed guard suppresses false-positive when NamespacePods list fails (#88 / #90)
	listFailedSnap := emptyPodsSnap
	listFailedSnap.PodListFailed = true
	if vsListFailed := rule.Evaluate(&listFailedSnap); len(vsListFailed) != 0 {
		t.Fatalf("expected 0 violations when PodListFailed=true, got %+v", vsListFailed)
	}
}

func TestI10_RestoringReplacementLiveness_GreenProof(t *testing.T) {
	greenPath := filepath.Join("testdata", "i10_wedged_restoring_orphan_green_snapshots.json")
	raw, err := os.ReadFile(greenPath)
	if err != nil {
		t.Fatalf("read GREEN snapshot corpus %s: %v", greenPath, err)
	}
	var snaps []ReconcileSnapshot
	if err := json.Unmarshal(raw, &snaps); err != nil {
		t.Fatalf("unmarshal GREEN snapshot corpus %s: %v", greenPath, err)
	}
	if len(snaps) == 0 {
		t.Fatalf("expected non-empty GREEN snapshot corpus in %s", greenPath)
	}
	rule := RuleI10()
	exercisedPast30s := 0
	exercisedPrimaryPodFallback := 0
	for i := range snaps {
		if vs := rule.Evaluate(&snaps[i]); len(vs) != 0 {
			t.Fatalf("GREEN proof failed at step %d (now=%s): unexpected false-positive violation %+v", i, snaps[i].Now.Format("2006-01-02T15:04:05Z07:00"), vs)
		}
		if snaps[i].PrimaryPMJ != nil &&
			snaps[i].PrimaryPMJ.Status.RestoringStartTime != nil &&
			snaps[i].Now.Sub(snaps[i].PrimaryPMJ.Status.RestoringStartTime.Time).Seconds() >= 30 {
			exercisedPast30s++
			if len(snaps[i].NamespacePods) == 0 && snaps[i].PrimaryPod != nil {
				exercisedPrimaryPodFallback++
			}
		}
	}
	if exercisedPast30s < 5 {
		t.Fatalf("expected GREEN corpus to include >= 5 PhaseRestoring snapshots past the 30s gate, got %d", exercisedPast30s)
	}
	if exercisedPrimaryPodFallback < 1 {
		t.Fatalf("expected GREEN corpus to exercise the PrimaryPod fallback (empty NamespacePods) at least once, got %d", exercisedPrimaryPodFallback)
	}
}

