apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-migration-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-migration-controller
  template:
    metadata:
      labels:
        app: pod-migration-controller
    spec:
      serviceAccountName: pod-migration-controller
      containers:
      - name: manager
        image: pod-migration:latest
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-cert
