apiVersion: v1
kind: Namespace
metadata:
  name: pod-migration-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-migration-controller
  namespace: pod-migration-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-migration-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - podmigration.gke.io
  resources:
  - podmigrationjobs
  - podmigrations
  - podmigrationjobs/status
  - podmigrations/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podsnapshot.gke.io
  resources:
  - podsnapshotmanualtriggers
  - podsnapshotpolicies
  - podsnapshotstorageconfigs
  - podsnapshotstorageconfigs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podsnapshot.gke.io
  resources:
  - podsnapshots
  - podsnapshots/status
  - podsnapshotpolicies/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pm-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-migration-controller-role
subjects:
- kind: ServiceAccount
  name: pod-migration-controller
  namespace: pod-migration-system
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: pod-migration-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
  namespace: pod-migration-system
spec:
  dnsNames:
  - webhook-service.pod-migration-system.svc
  - webhook-service.pod-migration-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-migration-controller
  namespace: pod-migration-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pod-migration-controller
  template:
    metadata:
      labels:
        app: pod-migration-controller
    spec:
      serviceAccountName: pod-migration-controller
      containers:
      - name: manager
        image: <YOUR_CONTROLLER_IMAGE>
        imagePullPolicy: Always
        command:
        - /manager
        args:
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: pod-migration-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: pod-migration-controller
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: pod-migration-system/webhook-cert
webhooks:
  - name: veviction.podmigration.gke.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 5
    clientConfig:
      service:
        namespace: pod-migration-system
        name: webhook-service
        path: /validate--v1-pod-eviction
        port: 443
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - pod-migration-system
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods/eviction"]
        scope: Namespaced
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: pod-migration-system/webhook-cert
webhooks:
  - name: mpodgate.podmigration.gke.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 5
    clientConfig:
      service:
        namespace: pod-migration-system
        name: webhook-service
        path: /mutate-v1-pod-scheduling-gate
        port: 443
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - pod-migration-system
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
